/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  bookSidebar: [
    {
      type: 'doc',
      id: 'about-this-book',
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/why-agile',
        'concepts/testing-concepts',
        'concepts/why-tdd',
        'concepts/outside-in-tdd',
      ],
    },
    {
      type: 'category',
      label: 'Exercise',
      link: {type: 'doc', id: 'exercise'},
      items: [
        {
          type: 'category',
          label: 'React',
          link: {type: 'doc', id: 'react/index'},
          items: [
            {type: 'doc', id: 'react/project-setup', label: 'Project Setup'},
            {type: 'doc', id: 'react/vertical-slice', label: 'Vertical Slice'},
            {
              type: 'doc',
              id: 'react/refactoring-styles',
              label: 'Refactoring Styles',
            },
            {type: 'doc', id: 'react/edge-cases', label: 'Edge Cases'},
            {type: 'doc', id: 'react/writing-data', label: 'Writing Data'},
          ],
        },
        {
          type: 'category',
          label: 'Vue',
          link: {type: 'doc', id: 'vue/index'},
          items: [
            {type: 'doc', id: 'vue/project-setup', label: 'Project Setup'},
            {type: 'doc', id: 'vue/vertical-slice', label: 'Vertical Slice'},
            {
              type: 'doc',
              id: 'vue/refactoring-styles',
              label: 'Refactoring Styles',
            },
            {type: 'doc', id: 'vue/edge-cases', label: 'Edge Cases'},
            {type: 'doc', id: 'vue/writing-data', label: 'Writing Data'},
          ],
        },
        'exercise-wrap-up',
      ],
    },
    {
      type: 'doc',
      id: 'next-steps',
    },
  ],
};

module.exports = sidebars;
